package:
  name: cmaes 
  version: 0.9.2

source:
    git_tag: b91c184edeb9e46aa57ffb176cd5e79de1e6d49a 
    git_url: https://github.com/mehdidc/libcmaes

requirements:
    build:
        - python
        - numpy
        - boost
        - boost-python
    run:
        - python
        - numpy
        - boost
        - boost-python
about:
  home: https://github.com/beniz/libcmaes
  license: LGPLv3
