package:
  name: cmaes 
  version: 0.9.5

source:
    git_tag: conda_last
    git_url: https://github.com/mehdidc/libcmaes

requirements:
    build:
        - python
        - numpy
        - boost
        - boost-python
    run:
        - python
        - numpy
        - boost
        - boost-python
about:
  home: https://github.com/beniz/libcmaes
  license: LGPLv3
