package:
  name: lcmaes 
  version: 0.2.14

source:
    git_url: https://github.com/mehdidc/libcmaes

requirements:
    build:
        - python
    run:
        - python

about:
  home: https://github.com/beniz/libcmaes
  license: BSD
